"""empty message

Revision ID: 0cecafd11b1d
Revises: 577efd04f4b1
Create Date: 2017-03-14 04:19:43.495630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cecafd11b1d'
down_revision = '577efd04f4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###
