"""empty message

Revision ID: 577efd04f4b1
Revises: 772ce2b3b700
Create Date: 2017-03-12 11:58:24.171543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577efd04f4b1'
down_revision = '772ce2b3b700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('date', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'date')
    # ### end Alembic commands ###
